repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: 'v0.43.0'
  hooks:
  - id: markdownlint
    args: ["-c", ".markdownlint.json"]
  - id: markdownlint-fix
    args: ["-c", ".markdownlint.json"]
# -   repo: local
#     hooks:
#     -   id: check-obsidian-links
#         name: Check Obsidian Links
#         entry: python scripts/check_obsidian_links.py
#         language: python
#         types: [markdown]
#         pass_filenames: false
